<?php

/**
 * This is the model base class for the table "tipo_pagamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoPagamento".
 *
 * Columns in table "tipo_pagamento" available as properties of the model,
 * followed by relations of table "tipo_pagamento" available as properties of the model.
 *
 * @property integer $id_tipo_pagamento
 * @property string $nome
 *
 * @property Compra[] $compras
 */
abstract class BaseTipoPagamento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_pagamento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoPagamento|TipoPagamentos', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>45),
			array('nome', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tipo_pagamento, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'compras' => array(self::HAS_MANY, 'Compra', 'id_tipo_pagamento'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tipo_pagamento' => Yii::t('app', 'Id Tipo Pagamento'),
			'nome' => Yii::t('app', 'Nome'),
			'compras' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tipo_pagamento', $this->id_tipo_pagamento);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}