<?php

/**
 * This is the model base class for the table "endereco".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Endereco".
 *
 * Columns in table "endereco" available as properties of the model,
 * followed by relations of table "endereco" available as properties of the model.
 *
 * @property integer $id_endereco
 * @property string $nome
 * @property string $cep
 * @property integer $tipo
 * @property string $rua
 * @property string $numero
 * @property string $complemento
 * @property string $descricao
 * @property string $bairro
 * @property integer $id_cidade
 *
 * @property Cidade $idCidade
 * @property Fornecedor[] $fornecedors
 * @property Funcionario[] $funcionarios
 * @property PessoaHasEndereco[] $pessoaHasEnderecos
 */
abstract class BaseEndereco extends GxActiveRecord {

        public $local_novo;
    
        public $pais_novo;
        
        public $estado_novo;
        
        public $cidade_nova;
    
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'endereco';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Endereco|Enderecos', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome, cep, rua, numero, bairro, id_cidade, id_pais', 'required'),
			array('tipo, id_cidade', 'numerical', 'integerOnly'=>true),
			array('nome, rua, bairro', 'length', 'max'=>120),
			array('cep', 'length', 'max'=>9),
			array('numero', 'length', 'max'=>5),
			array('complemento', 'length', 'max'=>45),
			array('descricao', 'safe'),
			array('tipo, complemento, descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_endereco, nome, cep, tipo, rua, numero, complemento, descricao, bairro, id_cidade', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idCidade' => array(self::BELONGS_TO, 'Cidade', 'id_cidade'),
			'fornecedors' => array(self::HAS_MANY, 'Fornecedor', 'id_endereco'),
			'funcionarios' => array(self::HAS_MANY, 'Funcionario', 'id_endereco'),
			'pessoaHasEnderecos' => array(self::HAS_MANY, 'PessoaHasEndereco', 'id_endereco'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_endereco' => Yii::t('app', 'Id Endereco'),
			'nome' => Yii::t('app', 'Nome'),
			'cep' => Yii::t('app', 'CEP'),
			'tipo' => Yii::t('app', 'Tipo'),
			'rua' => Yii::t('app', 'Rua'),
			'numero' => Yii::t('app', 'Número'),
			'complemento' => Yii::t('app', 'Complemento'),
			'descricao' => Yii::t('app', 'Descrição'),
			'bairro' => Yii::t('app', 'Bairro'),
			'id_cidade' => 'Cidade',
			'idCidade' => null,
			'fornecedors' => null,
			'funcionarios' => null,
			'pessoaHasEnderecos' => null,
                        'id_pais' => 'País',
                        'id_estado' => 'Estado',
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_endereco', $this->id_endereco);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('cep', $this->cep, true);
		$criteria->compare('tipo', $this->tipo);
		$criteria->compare('rua', $this->rua, true);
		$criteria->compare('numero', $this->numero, true);
		$criteria->compare('complemento', $this->complemento, true);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('bairro', $this->bairro, true);
		$criteria->compare('id_cidade', $this->id_cidade);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}