<?php

/**
 * This is the model base class for the table "tipo_contato".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoContato".
 *
 * Columns in table "tipo_contato" available as properties of the model,
 * followed by relations of table "tipo_contato" available as properties of the model.
 *
 * @property integer $id_tipo_contato
 * @property string $area
 *
 * @property Contato[] $contatos
 */
abstract class BaseTipoContato extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_contato';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoContato|TipoContatos', $n);
	}

	public static function representingColumn() {
		return 'area';
	}

	public function rules() {
		return array(
			array('area', 'length', 'max'=>120),
			array('area', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tipo_contato, area', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'contatos' => array(self::HAS_MANY, 'Contato', 'id_tipo_contato'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tipo_contato' => Yii::t('app', 'Id Tipo Contato'),
			'area' => Yii::t('app', 'Area'),
			'contatos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tipo_contato', $this->id_tipo_contato);
		$criteria->compare('area', $this->area, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}