<?php

/**
 * This is the model base class for the table "pessoa_has_endereco".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PessoaHasEndereco".
 *
 * Columns in table "pessoa_has_endereco" available as properties of the model,
 * followed by relations of table "pessoa_has_endereco" available as properties of the model.
 *
 * @property integer $id_pessoa_has_endereco
 * @property integer $id_pessoa_fisica
 * @property integer $id_pessoa_juridica
 * @property integer $id_endereco
 * @property integer $preferencial
 *
 * @property Endereco $idEndereco
 * @property PessoaFisica $idPessoaFisica
 * @property PessoaJuridica $idPessoaJuridica
 */
abstract class BasePessoaHasEndereco extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pessoa_has_endereco';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PessoaHasEndereco|PessoaHasEnderecos', $n);
	}

	public static function representingColumn() {
		return 'id_pessoa_has_endereco';
	}

	public function rules() {
		return array(
			array('id_endereco', 'required'),
			array('id_pessoa_fisica, id_pessoa_juridica, id_endereco, preferencial', 'numerical', 'integerOnly'=>true),
			array('id_pessoa_fisica, id_pessoa_juridica, preferencial', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_pessoa_has_endereco, id_pessoa_fisica, id_pessoa_juridica, id_endereco, preferencial', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idEndereco' => array(self::BELONGS_TO, 'Endereco', 'id_endereco'),
			'idPessoaFisica' => array(self::BELONGS_TO, 'PessoaFisica', 'id_pessoa_fisica'),
			'idPessoaJuridica' => array(self::BELONGS_TO, 'PessoaJuridica', 'id_pessoa_juridica'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_pessoa_has_endereco' => Yii::t('app', 'Id Pessoa Has Endereco'),
			'id_pessoa_fisica' => null,
			'id_pessoa_juridica' => null,
			'id_endereco' => null,
			'preferencial' => Yii::t('app', 'Preferencial'),
			'idEndereco' => null,
			'idPessoaFisica' => null,
			'idPessoaJuridica' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_pessoa_has_endereco', $this->id_pessoa_has_endereco);
		$criteria->compare('id_pessoa_fisica', $this->id_pessoa_fisica);
		$criteria->compare('id_pessoa_juridica', $this->id_pessoa_juridica);
		$criteria->compare('id_endereco', $this->id_endereco);
		$criteria->compare('preferencial', $this->preferencial);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}