<?php

/**
 * This is the model base class for the table "sub_departamento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SubDepartamento".
 *
 * Columns in table "sub_departamento" available as properties of the model,
 * followed by relations of table "sub_departamento" available as properties of the model.
 *
 * @property integer $id_sub_departamento
 * @property string $nome
 * @property integer $id_departamento
 *
 * @property Produto[] $produtos
 * @property Departamento $idDepartamento
 */
abstract class BaseSubDepartamento extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sub_departamento';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SubDepartamento|SubDepartamentos', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome, id_departamento', 'required'),
			array('id_departamento', 'numerical', 'integerOnly'=>true),
			array('nome', 'length', 'max'=>120),
			array('id_sub_departamento, nome, id_departamento', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'produtos' => array(self::HAS_MANY, 'Produto', 'id_sub_departamento'),
			'idDepartamento' => array(self::BELONGS_TO, 'Departamento', 'id_departamento'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_sub_departamento' => Yii::t('app', 'Id Sub Departamento'),
			'nome' => Yii::t('app', 'Nome'),
			'id_departamento' => null,
			'produtos' => null,
			'idDepartamento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_sub_departamento', $this->id_sub_departamento);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('id_departamento', $this->id_departamento);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}