<?php

/**
 * This is the model base class for the table "promocao_has_produto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PromocaoHasProduto".
 *
 * Columns in table "promocao_has_produto" available as properties of the model,
 * followed by relations of table "promocao_has_produto" available as properties of the model.
 *
 * @property integer $id_promocao_has_produto
 * @property integer $id_promocao
 * @property integer $id_produto
 * @property integer $desconto
 * @property integer $quantidade
 * @property integer $quantidade_vendida
 *
 * @property Promocao $idPromocao
 * @property Produto $idProduto
 */
abstract class BasePromocaoHasProduto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'promocao_has_produto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PromocaoHasProduto|PromocaoHasProdutos', $n);
	}

	public static function representingColumn() {
		return 'id_promocao_has_produto';
	}

	public function rules() {
		return array(
			array('id_promocao, id_produto', 'required'),
			array('id_promocao, id_produto, desconto, quantidade, quantidade_vendida', 'numerical', 'integerOnly'=>true),
			array('desconto, quantidade, quantidade_vendida', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_promocao_has_produto, id_promocao, id_produto, desconto, quantidade, quantidade_vendida', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idPromocao' => array(self::BELONGS_TO, 'Promocao', 'id_promocao'),
			'idProduto' => array(self::BELONGS_TO, 'Produto', 'id_produto'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_promocao_has_produto' => Yii::t('app', 'Id Promocao Has Produto'),
			'id_promocao' => null,
			'id_produto' => null,
			'desconto' => Yii::t('app', 'Desconto'),
			'quantidade' => Yii::t('app', 'Quantidade'),
			'quantidade_vendida' => Yii::t('app', 'Quantidade Vendida'),
			'idPromocao' => null,
			'idProduto' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_promocao_has_produto', $this->id_promocao_has_produto);
		$criteria->compare('id_promocao', $this->id_promocao);
		$criteria->compare('id_produto', $this->id_produto);
		$criteria->compare('desconto', $this->desconto);
		$criteria->compare('quantidade', $this->quantidade);
		$criteria->compare('quantidade_vendida', $this->quantidade_vendida);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}