<?php

/**
 * This is the model base class for the table "marca".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Marca".
 *
 * Columns in table "marca" available as properties of the model,
 * followed by relations of table "marca" available as properties of the model.
 *
 * @property integer $id_marca
 * @property string $nome
 *
 * @property Produto[] $produtos
 */
abstract class BaseMarca extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'marca';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Marca|Marcas', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>120),
			array('nome', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_marca, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'produtos' => array(self::HAS_MANY, 'Produto', 'id_marca'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_marca' => Yii::t('app', 'Id Marca'),
			'nome' => Yii::t('app', 'Nome'),
			'produtos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_marca', $this->id_marca);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}