<?php

/**
 * This is the model base class for the table "especificacao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Especificacao".
 *
 * Columns in table "especificacao" available as properties of the model,
 * followed by relations of table "especificacao" available as properties of the model.
 *
 * @property integer $id_especificacao
 * @property string $nome
 *
 * @property ProdutoHasEspecificacao[] $produtoHasEspecificacaos
 */
abstract class BaseEspecificacao extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'especificacao';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Especificacao|Especificacaos', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>120),
			array('nome', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_especificacao, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'produtoHasEspecificacaos' => array(self::HAS_MANY, 'ProdutoHasEspecificacao', 'id_especificacao'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_especificacao' => Yii::t('app', 'Id Especificacao'),
			'nome' => Yii::t('app', 'Nome'),
			'produtoHasEspecificacaos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_especificacao', $this->id_especificacao);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}