<?php

/**
 * This is the model base class for the table "compra_has_produto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompraHasProduto".
 *
 * Columns in table "compra_has_produto" available as properties of the model,
 * followed by relations of table "compra_has_produto" available as properties of the model.
 *
 * @property integer $id_compra_has_produto
 * @property integer $id_compra
 * @property integer $id_produto
 *
 * @property Produto $idProduto
 * @property Compra $idCompra
 */
abstract class BaseCompraHasProduto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'compra_has_produto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompraHasProduto|CompraHasProdutos', $n);
	}

	public static function representingColumn() {
		return 'id_compra_has_produto';
	}

	public function rules() {
		return array(
			array('id_compra, id_produto', 'required'),
			array('id_compra, id_produto', 'numerical', 'integerOnly'=>true),
			array('id_compra_has_produto, id_compra, id_produto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idProduto' => array(self::BELONGS_TO, 'Produto', 'id_produto'),
			'idCompra' => array(self::BELONGS_TO, 'Compra', 'id_compra'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_compra_has_produto' => Yii::t('app', 'Id Compra Has Produto'),
			'id_compra' => null,
			'id_produto' => null,
			'idProduto' => null,
			'idCompra' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_compra_has_produto', $this->id_compra_has_produto);
		$criteria->compare('id_compra', $this->id_compra);
		$criteria->compare('id_produto', $this->id_produto);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}