<?php

/**
 * This is the model base class for the table "promocao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Promocao".
 *
 * Columns in table "promocao" available as properties of the model,
 * followed by relations of table "promocao" available as properties of the model.
 *
 * @property integer $id_promocao
 * @property string $data_inicio
 * @property string $data_fim
 * @property integer $ativo
 *
 * @property PromocaoHasProduto[] $promocaoHasProdutos
 */
abstract class BasePromocao extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'promocao';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Promocao|Promocaos', $n);
	}

	public static function representingColumn() {
		return 'data_inicio';
	}

	public function rules() {
		return array(
			array('data_inicio', 'required'),
			array('ativo', 'numerical', 'integerOnly'=>true),
			array('data_fim', 'safe'),
			array('data_fim, ativo', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_promocao, data_inicio, data_fim, ativo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'promocaoHasProdutos' => array(self::HAS_MANY, 'PromocaoHasProduto', 'id_promocao'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_promocao' => Yii::t('app', 'Id Promocao'),
			'data_inicio' => Yii::t('app', 'Data Inicio'),
			'data_fim' => Yii::t('app', 'Data Fim'),
			'ativo' => Yii::t('app', 'Ativo'),
			'promocaoHasProdutos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_promocao', $this->id_promocao);
		$criteria->compare('data_inicio', $this->data_inicio, true);
		$criteria->compare('data_fim', $this->data_fim, true);
		$criteria->compare('ativo', $this->ativo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}