<?php

/**
 * This is the model base class for the table "departamento_has_funcionario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DepartamentoHasFuncionario".
 *
 * Columns in table "departamento_has_funcionario" available as properties of the model,
 * followed by relations of table "departamento_has_funcionario" available as properties of the model.
 *
 * @property integer $id_departamento_has_funcionario
 * @property integer $id_departamento
 * @property integer $id_funcionario
 *
 * @property Departamento $idDepartamento
 * @property Funcionario $idFuncionario
 */
abstract class BaseDepartamentoHasFuncionario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'departamento_has_funcionario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DepartamentoHasFuncionario|DepartamentoHasFuncionarios', $n);
	}

	public static function representingColumn() {
		return 'id_departamento_has_funcionario';
	}

	public function rules() {
		return array(
			array('id_departamento, id_funcionario', 'required'),
			array('id_departamento, id_funcionario', 'numerical', 'integerOnly'=>true),
			array('id_departamento_has_funcionario, id_departamento, id_funcionario', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idDepartamento' => array(self::BELONGS_TO, 'Departamento', 'id_departamento'),
			'idFuncionario' => array(self::BELONGS_TO, 'Funcionario', 'id_funcionario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_departamento_has_funcionario' => Yii::t('app', 'Id Departamento Has Funcionario'),
			'id_departamento' => null,
			'id_funcionario' => null,
			'idDepartamento' => null,
			'idFuncionario' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_departamento_has_funcionario', $this->id_departamento_has_funcionario);
		$criteria->compare('id_departamento', $this->id_departamento);
		$criteria->compare('id_funcionario', $this->id_funcionario);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}