<?php

/**
 * This is the model base class for the table "status_compra".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StatusCompra".
 *
 * Columns in table "status_compra" available as properties of the model,
 * followed by relations of table "status_compra" available as properties of the model.
 *
 * @property integer $id_status_compra
 * @property string $nome
 *
 * @property Compra[] $compras
 */
abstract class BaseStatusCompra extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'status_compra';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StatusCompra|StatusCompras', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'required'),
			array('nome', 'length', 'max'=>45),
			array('id_status_compra, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'compras' => array(self::HAS_MANY, 'Compra', 'id_status_compra'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_status_compra' => Yii::t('app', 'Id Status Compra'),
			'nome' => Yii::t('app', 'Nome'),
			'compras' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_status_compra', $this->id_status_compra);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}