<?php

/**
 * This is the model base class for the table "pessoa_juridica".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PessoaJuridica".
 *
 * Columns in table "pessoa_juridica" available as properties of the model,
 * followed by relations of table "pessoa_juridica" available as properties of the model.
 *
 * @property integer $id_pessoa_juridica
 * @property string $razao_social
 * @property string $nome_fantasia
 * @property string $cnpj
 * @property string $insc_estadual
 * @property string $email
 *
 * @property Cliente[] $clientes
 * @property Fornecedor[] $fornecedors
 * @property PessoaHasEndereco[] $pessoaHasEnderecos
 * @property PessoaHasTelefone[] $pessoaHasTelefones
 */
abstract class BasePessoaJuridica extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pessoa_juridica';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PessoaJuridica|PessoaJuridicas', $n);
	}

	public static function representingColumn() {
		return 'razao_social';
	}

	public function rules() {
		return array(
			array('razao_social, cnpj, email', 'required'),
			array('razao_social, nome_fantasia, email', 'length', 'max'=>120),
			array('cnpj', 'length', 'max'=>18),
			array('insc_estadual', 'length', 'max'=>8),
			array('nome_fantasia, insc_estadual', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_pessoa_juridica, razao_social, nome_fantasia, cnpj, insc_estadual, email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientes' => array(self::HAS_MANY, 'Cliente', 'id_pessoa_juridica'),
			'fornecedors' => array(self::HAS_MANY, 'Fornecedor', 'id_pessoa_juridica'),
			'pessoaHasEnderecos' => array(self::HAS_MANY, 'PessoaHasEndereco', 'id_pessoa_juridica'),
			'pessoaHasTelefones' => array(self::HAS_MANY, 'PessoaHasTelefone', 'id_pessoa_juridica'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_pessoa_juridica' => Yii::t('app', 'Id Pessoa Juridica'),
			'razao_social' => Yii::t('app', 'Razão Social'),
			'nome_fantasia' => Yii::t('app', 'Nome Fantasia'),
			'cnpj' => Yii::t('app', 'CNPJ'),
			'insc_estadual' => Yii::t('app', 'Inscrição Estadual'),
			'email' => Yii::t('app', 'Email'),
			'clientes' => null,
			'fornecedors' => null,
			'pessoaHasEnderecos' => null,
			'pessoaHasTelefones' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_pessoa_juridica', $this->id_pessoa_juridica);
		$criteria->compare('razao_social', $this->razao_social, true);
		$criteria->compare('nome_fantasia', $this->nome_fantasia, true);
		$criteria->compare('cnpj', $this->cnpj, true);
		$criteria->compare('insc_estadual', $this->insc_estadual, true);
		$criteria->compare('email', $this->email, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}