<?php

/**
 * This is the model base class for the table "produto_has_especificacao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProdutoHasEspecificacao".
 *
 * Columns in table "produto_has_especificacao" available as properties of the model,
 * followed by relations of table "produto_has_especificacao" available as properties of the model.
 *
 * @property integer $id_produto_has_especificacao
 * @property string $valor
 * @property integer $id_especificacao
 * @property integer $id_produto
 *
 * @property Especificacao $idEspecificacao
 * @property Produto $idProduto
 */
abstract class BaseProdutoHasEspecificacao extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'produto_has_especificacao';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProdutoHasEspecificacao|ProdutoHasEspecificacaos', $n);
	}

	public static function representingColumn() {
		return 'valor';
	}

	public function rules() {
		return array(
			array('id_especificacao, id_produto', 'required'),
			array('id_especificacao, id_produto', 'numerical', 'integerOnly'=>true),
			array('valor', 'length', 'max'=>120),
			array('valor', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_produto_has_especificacao, valor, id_especificacao, id_produto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idEspecificacao' => array(self::BELONGS_TO, 'Especificacao', 'id_especificacao'),
			'idProduto' => array(self::BELONGS_TO, 'Produto', 'id_produto'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_produto_has_especificacao' => Yii::t('app', 'Id Produto Has Especificacao'),
			'valor' => Yii::t('app', 'Valor'),
			'id_especificacao' => null,
			'id_produto' => null,
			'idEspecificacao' => null,
			'idProduto' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_produto_has_especificacao', $this->id_produto_has_especificacao);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('id_especificacao', $this->id_especificacao);
		$criteria->compare('id_produto', $this->id_produto);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}